### PR TITLE
Validated

### PR DESCRIPTION
**Pull request by dcampogiani**
Using Strings to represents errors atm.

A sealed class would be a better choice.

Based on: https://github.com/DanielaSfregola/data-validation

### CODE REVIEW

**Comment by AL333Z** [comment]
Nice!
Is there in kategory the cartesian operator? (e.g. https://underscore.io/blog/posts/2015/06/10/an-introduction-to-cats.html or https://sihil.net/cats-validated.html)

If not, we may think to implement the same as an excercise.

**Comment by azanin** [comment]
Awesome.
Do you think is it worth to add Applicative definition, laws and some operator implementation (thinking about apply, pure,map2). I can try to do it in scala

**Comment by dcampogiani** [comment]
> Nice!
> Is there in kategory the cartesian operator? 
> 

|@| ? @AL333Z

**Review by azanin — APPROVED** [review]

**Comment by dcampogiani** [comment]
> Awesome.
> Do you think is it worth to add Applicative definition, laws and some operator implementation (thinking about apply, pure,map2). I can try to do it in scala

I know nothing about that stuff. @azanin

**Comment by azanin** [comment]
@dcampogiani https://github.com/azanin/fpInScala/commit/232b99df7ec6946546bb6285f8c9a2c958f9fee5

**Comment by pakoito** [comment]
@AL333Z We do have Applicative builders, yes! https://github.com/kategory/kategory/blob/master/kategory-docs/docs/docs/typeclasses/applicative/README.md#applicative-builder-examples

If there is anything you're missing do ping us and we'll take a look 💃

**Comment by AL333Z** [comment]
@pakoito that's great!
Keep up the good work!

**Review by AL333Z — APPROVED** [review]

**Pull request merged**
