### PR TITLE
Monad

### PR DESCRIPTION
**Pull request by dcampogiani**
Steps:
 - concatenate multiple flatmaps using sequential method invocation
 - for comprehension for Option
 - for comprehension for Either
 - polymorphic way

### CODE REVIEW

**Comment by dcampogiani** [comment]
Any feedback ? @generalim @azanin @massimobertuzzi @AL333Z

**Comment by AL333Z** [comment]
Rename Monad to Sequenceable?
You know.. all these mathematicians are really bad at naming things.

Joking..
:shipit:

**Review by AL333Z — APPROVED** [review]

**Comment by azanin** [comment]
Awesome

**Comment by dcampogiani** [comment]
@AL333Z @azanin does it make sense to update MonadErrorFunctions.kt to use

```kotlin
MonadError<F, SomeSubclassOfThrowable>
```

?

So that from outside we can invoke the polymorphic approach using:
 - try
 - left
 - Observable (arrow has an integration module registering the Monad Error Instance for Observable)

**Comment by dcampogiani** [comment]
@AL333Z 
>Rename Monad to Sequenceable?

Will do in a separate PR, thanks for hint.

**Comment by AL333Z** [comment]
It could make sense of course.
But I think that you may find some troubles with Try and Observables, which both raise Throwable.

You may give it a try and see what issue will emerge (converting a Throwable to a more-specific Throwable..).

Usually we do this with Either, since the `L` type is free and we can then define our ADT for errors.

**Pull request merged**
